include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.graphql.dart"
    - "lib/generated_plugin_registrant.dart"
    - ".test_coverage.dart"
    - "lib/firebase_options.dart"
  errors:
    todo: ignore
    invalid_annotation_target: ignore
    undefined_prefixed_name: ignore

linter:
  rules:
    public_member_api_docs: false
